import type { Metadata } from "next";
import { bricolageGrotesque, plusJakartaSans, kaushanScript } from "@/lib/fonts";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import CartDrawer from "@/components/cart/CartDrawer";
import DemoBanner from "@/components/system/DemoBanner";
import CustomCursor from "@/components/system/CustomCursor";
import { CartIconPositionProvider } from "@/context/CartIconPositionContext";
import FlyToCartLayer from "@/components/cart/FlyToCartLayer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${bricolageGrotesque.variable} ${plusJakartaSans.variable} ${kaushanScript.variable}`}
    >
      <body>
        <CartProvider>
          <CartIconPositionProvider>
            <DemoBanner />
            <CustomCursor />
            <Navbar />
            {children}
            <CartDrawer />
            <FlyToCartLayer />
            <Footer />
          </CartIconPositionProvider>
        </CartProvider>
      </body>
    </html>
  );
}
